---
hero_image: images/banner.png
listed: true
ingredient: false
title: Генератор віршів Ади
description: Відзначай День Ади Лавлейс, навчившись програмувати власний генератор віршів!
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: Introduction
  - 
    title: Ада Лавлейс
  - 
    title: 'Завдання: Запрограмуй Аду, щоб вона представилась'
    challenge: true
  - 
    title: Скажи Аді своє ім’я
  - 
    title: Аналітична машина
  - 
    title: Більше поезії
  - 
    title: Анімація аналітичної машини
  - 
    title: 'Challenge: Personalise your poem'
    challenge: true
  - 
    title: 'Завдання: Більше слів'
    challenge: true
  - 
    title: 'Challenge: More poetry'
    challenge: true
  - 
    title: What next?
