---
hero_image: images/banner.png
listed: true
ingredient: false
title: Ada's Poetry Generator
description: Celebrate Ada Lovelace Day, by learning how to program your own poetry generator!
version: 4
last_tested: 2019-02-20
steps: 
- title: Introduction
- title: Ada Lovelace
- title: 'Challenge: Code Ada to introduce herself'
  challenge: true
- title: Telling Ada your name
- title: The Analytical Engine
- title: More poetry
- title: Animating the Analytical Engine
- title: 'Challenge: Personalise your poem'
  challenge: true
- title: 'Challenge: More words'
  challenge: true
- title: 'Challenge: More poetry'
  challenge: true