---
hero_image: images/banner.png
listed: true
ingredient: false
title: Ada's Poetry Generator
description: Fejr Ada Lovelace Day ved at lære at programmere din egen digtergenerator!
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: Tillykke Med Fødselsdagen
  - 
    title: Ada Lovelace
  - 
    title: 'Udfordring: Kode Ada for at præsentere sig selv'
    completion:
      - engaged
    challenge: true
  - 
    title: Fortæller Ada dit navn
  - 
    title: Den analytiske motor
  - 
    title: Mere poesi
  - 
    title: Animering af den analytiske motor
    completion:
      - internal
  - 
    title: 'Udfordring: Tilpas dit digt'
    challenge: true
  - 
    title: 'Udfordring: Flere ord'
    challenge: true
  - 
    title: 'Udfordring: Mere poesi'
    challenge: true
  - 
    title: Hvad er næste skridt?
