---
hero_image: images/banner.png
listed: true
ingredient: false
title: Gerador de Poesia da Ada
description: Celebra o dia da Ada Lovelace, aprendendo a programar o teu próprio gerador
  de poesia!
version: 4
last_tested: 2019-02-20
steps:
- title: Introdução
  completion: engaged
- title: Ada Lovelace
- title: 'Desafio: Programa a Ada para te apresentares'
  challenge: true
- title: Dizer à Ada o teu nome
- title: O Motor Analítico
- title: Mais poesia
  completion: internal
- title: Animar o Motor Analítico
- title: 'Desafio: Personaliza o teu poema'
  challenge: true
- title: 'Desafio: Mais palavras'
  challenge: true
- title: 'Desafio: Mais poesia'
  challenge: true
- title: O que se segue?
