---
hero_image: images/banner.png
listed: true
ingredient: false
title: 艾达的诗歌生成器
description: 通过学习编写自己的诗歌生成器，来庆祝艾达·洛芙蕾丝日！
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: 介绍
  - 
    title: 艾达·洛芙蕾丝（Ada Lovelace）
  - 
    title: '挑战：通过艾达来介绍自己'
    completion:
      - engaged
    challenge: true
  - 
    title: 告诉艾达你的名字
  - 
    title: 分析引擎
  - 
    title: 更多的诗歌
  - 
    title: 给分析引擎添加动画
    completion:
      - internal
  - 
    title: '挑战：个性化您的诗'
    challenge: true
  - 
    title: '挑战：更多单词'
    challenge: true
  - 
    title: '挑战：更多诗歌'
    challenge: true
  - 
    title: 接下来呢？
