---
hero_image: images/banner.png
listed: true
ingredient: false
title: Generator poezije Ada
description: Proslavite Dan Ada Lovelace naučivši kako programirati vlastiti generator poezije!
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: Sretan rođendan
  - 
    title: Ada Lovelace
  - 
    title: 'Izazov: Šifra Ada da se predstavi'
    completion:
      - engaged
    challenge: true
  - 
    title: Rekavši Ada svoje ime
  - 
    title: Analitički motor
  - 
    title: Više poezije
  - 
    title: Animiranje analitičkog motora
    completion:
      - internal
  - 
    title: 'Izazov: Prilagodite svoju pjesmu'
    challenge: true
  - 
    title: 'Izazov: Više riječi'
    challenge: true
  - 
    title: 'Izazov: Više poezije'
    challenge: true
  - 
    title: Što dalje?
