---
hero_image: images/banner.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Peiriant Barddoniaeth Ada
description: I ddathlu Diwrnod Ada Lovelace, dysga sut i raglenni peiriant barddoniaeth!
original_url: https://codeclubprojects.org/en-GB/scratch/poetry-generator
interests: literature
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
- title: Cyflwyniad
  completion: engaged
- title: Ada Lovelace
- title: 'Her: Codio Ada i gyflwyno ei hunan'
- title: Dweud dy enw wrth Ada
- title: Y Peiriant Dadansoddol
- title: Mwy o farddoniaeth
  completion: internal
- title: Animeiddio'r Peiriant Dadansoddol
- title: 'Her: Personoleiddio dy gerdd'
- title: 'Her: Mwy o eiriau'
- title: 'Her: Mwy o gerddi'
