---
hero_image: images/banner.png
listed: true
ingredient: false
title: Gerador de Poesia de Ada
description: Celebre o dia de Ada Lovelace, aprendendo a programar seu próprio gerador de poesia!
version: 4
last_tested: 2019-02-20
steps:
  - title: Introdução
  - title: Ada Lovelace
  - title: 'Desafio: Codifique Ada para se apresentar'
    challenge: true
  - title: Dizendo seu nome à Ada
  - title: O Motor Analítico
  - title: Mais poesia
  - title: Animando o Motor Analítico
  - title: 'Desafio: Personalize seu poema'
    challenge: true
  - title: 'Desafio: Mais palavras'
    challenge: true
  - title: 'Desafio: Mais poesia'
    challenge: true
  - title: E agora?
