---
hero_image: imatges / banner.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Generador de poesia de l'Ada
description: Celebreu el Dia d'Ada Lovelace, aprenent a programar el vostre propi generador de poesia!
original_url: https://codeclubprojects.org/en-GB/scratch/poetry-generator
interests: literatura
technologies: scratch
site_areas: projectes
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducció
  - 
    title: Ada Lovelace
  - 
    title: 'Repte: Programa l''Ada per a què es presenti'
  - 
    title: Digues-li el teu nom a l'Ada
  - 
    title: El motor analític
  - 
    title: Més poesia
  - 
    title: Animació del motor analític
  - 
    title: 'Repte: Personalitza el teu poema'
  - 
    title: 'Repte: Més paraules'
  - 
    title: 'Repte: Més poesia'
