---
hero_image: imatges / banner.png
listed: true
ingredient: false
title: Generador de poesia de l'Ada
description: Celebreu el Dia d'Ada Lovelace, aprenent a programar el vostre propi generador de poesia!
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: Introducció
  - 
    title: Ada Lovelace
  - 
    title: 'Repte: Programa l''Ada per a què es presenti'
    completion:
      - engaged
    challenge: true
  - 
    title: Digues-li el teu nom a l'Ada
  - 
    title: El motor analític
  - 
    title: Més poesia
  - 
    title: Animació del motor analític
    completion:
      - internal
  - 
    title: 'Repte: Personalitza el teu poema'
    challenge: true
  - 
    title: 'Repte: Més paraules'
    challenge: true
  - 
    title: 'Repte: Més poesia'
    challenge: true
  - 
    title: I ara què ve?
