---
hero_image: images/banner.png
listed: true
ingredient: false
title: Adin generator poezije
description: Praznujte dan Ane Lovelace, z učenjem programiranja lastnega generatorja poezije!
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: Uvod
  - 
    title: Ada Lovelace
  - 
    title: 'Izziv: Sprogramiraj Ado, da se predstavi'
    completion:
      - engaged
    challenge: true
  - 
    title: Povej Adi svoje ime
  - 
    title: Analitični pogon
  - 
    title: Več poezije
  - 
    title: Animiranje analitičnega pogona
    completion:
      - internal
  - 
    title: 'Izziv: Prilagodi svojo pesem'
    challenge: true
  - 
    title: 'Izziv: Več besed'
    challenge: true
  - 
    title: 'Izziv: Več poezije'
    challenge: true
  - 
    title: Kaj sledi?
