---
hero_image: images/banner.png
listed: true
ingredient: false
title: Generator poezije Ade
description: Praznujte dan Ane Lovelace z učenjem programiranja lastnega generatorja poezije!
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: Uvod
  - 
    title: Ada Lovelace
  - 
    title: 'Izziv: Code Ada, da se predstavi'
    challenge: true
  - 
    title: Povej Ada svoje ime
  - 
    title: Analitični motor
  - 
    title: Več poezije
  - 
    title: Animacija analitičnega motorja
  - 
    title: 'Izziv: Prilagodite svojo pesem'
    challenge: true
  - 
    title: 'Izziv: Več besed'
    challenge: true
  - 
    title: 'Izziv: Več poezije'
    challenge: true
  - 
    title: Kaj sledi?
