---
hero_image: images/banner.png
listed: true
ingredient: false
title: 艾達的詩歌生成器
description: 通過學習如何編寫自己的詩歌生成器來慶祝Ada Lovelace日！
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: 介紹
  - 
    title: 艾達·洛芙蕾絲（Ada Lovelace）
  - 
    title: '挑戰：Ada代碼介紹自己'
    completion:
      - engaged
    challenge: true
  - 
    title: 告訴阿達你的名字
  - 
    title: 分析引擎
  - 
    title: 多詩
  - 
    title: 動畫分析引擎
    completion:
      - internal
  - 
    title: '挑戰：個性化您的詩'
    challenge: true
  - 
    title: '挑戰：更多單詞'
    challenge: true
  - 
    title: '挑戰：更多詩歌'
    challenge: true
  - 
    title: 然後呢？
