---
hero_image: images/banner.png
listed: true
ingredient: false
title: Adin generátor poézie
description: Osláv Deň Ady Lovelace tým, že sa naučíš, ako naprogramovať svoj vlastný generátor básní!
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: Úvod
  - 
    title: Ada Lovelace
  - 
    title: 'Výzva: Naprogramuj Adu, aby sa sama predstavila'
    completion:
      - engaged
    challenge: true
  - 
    title: Povedz Ade svoje meno
  - 
    title: Analytický stroj
  - 
    title: Viac poézie
  - 
    title: Animácia analytického stroja
    completion:
      - internal
  - 
    title: 'Výzva: Prispôsob si svoju báseň'
    challenge: true
  - 
    title: 'Výzva: Viac slov'
    challenge: true
  - 
    title: 'Výzva: Viac poézie'
    challenge: true
  - 
    title: Čo ďalej?
