---
hero_image: images/banner.png
listed: true
ingredient: false
title: Η γεννήτρια ποίησης της Ada
description: Γιόρτασε την ημέρα της Ada Lovelace, μαθαίνοντας πώς να προγραμματίσεις τη δική σου γεννήτρια ποίησης!
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: Εισαγωγή
  - 
    title: Ada Lovelace
  - 
    title: 'Πρόκληση: Προγραμμάτισε την Ada να παρουσιάσει τον εαυτό της'
    completion:
      - engaged
    challenge: true
  - 
    title: Πες στην Ada το όνομά σου
  - 
    title: Η Αναλυτική Μηχανή
  - 
    title: Περισσότερη ποίηση
  - 
    title: Ενεργοποιώντας την Αναλυτική Μηχανή
    completion:
      - internal
  - 
    title: 'Πρόκληση: Εξατομίκευσε το ποίημά σου'
    challenge: true
  - 
    title: 'Πρόκληση: Περισσότερες λέξεις'
    challenge: true
  - 
    title: 'Πρόκληση: Περισσότερη ποίηση'
    challenge: true
  - 
    title: Τι υπάρχει στη συνέχεια;
