---
hero_image: images/banner.png
listed: true
ingredient: false
title: Générateur de poésie d'Ada
description: Célébrez la journée d'Ada Lovelace en apprenant à programmer votre propre générateur de poésie!
version: 4
last_tested: 2019-02-20
steps:
  - title: Introduction
  - title: Ada Lovelace
  - title: 'Défi: Code Ada se présente'
    challenge: true
  - title: Dire à Ada ton nom
  - title: Le moteur analytique
  - title: Plus de poésie
  - title: Animation du moteur analytique
  - title: 'Défi: personnalise ton poème'
    challenge: true
  - title: 'Défi: plus de mots'
    challenge: true
  - title: 'Défi: plus de poésie'
    challenge: true
  - title: Et ensuite?
