---
hero_image: images/banner.png
listed: true
ingredient: false
title: Il generatore di poesie di Ada
description: Festeggia la Giornata di Ada Lovelace, imparando a programmare il tuo generatore di poesie!
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: Introduzione
  - 
    title: Ada Lovelace
  - 
    title: 'Sfida: Programma Ada per presentarsi'
    challenge: true
  - 
    title: Dire ad Ada il tuo nome
  - 
    title: Il Motore Analitico
  - 
    title: Più poesia
  - 
    title: Animare il Motore Analitico
  - 
    title: 'Sfida: Personalizza la tua poesia'
    challenge: true
  - 
    title: 'Sfida: Altre parole'
    challenge: true
  - 
    title: 'Sfida: Più poesia'
    challenge: true
  - 
    title: E poi?
