---
hero_image: images/banner.png
listed: true
ingredient: false
title: Ada'nın Şiir Jeneratörü
description: Kendi şiir jeneratörünüzü nasıl programlayacağınızı öğrenerek Ada Lovelace Günü'nü kutlayın!
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: Giriş
  - 
    title: Ada Lovelace
  - 
    title: 'Zorluk: Ada''yı Kodla'
    challenge: true
  - 
    title: Ada'ya ismini söylemek
  - 
    title: Analitik Motor
  - 
    title: Daha fazla şiir
  - 
    title: Analitik Motorun Canlandırılması
  - 
    title: 'Zor Görev: Şiirinizi kişiselleştirin'
    challenge: true
  - 
    title: 'Zor Görev: Daha fazla kelime'
    challenge: true
  - 
    title: 'Zor Görev: Daha fazla şiir'
    challenge: true
  - 
    title: Sırada ne var?
