---
hero_image: images/banner.png
listed: true
ingredient: false
title: Ada'nın Şiir Oluşturucusu
description: Kendi şiir oluşturucunuzu nasıl programlayacağınızı öğrenerek Ada Lovelace Günü'nü kutlayın!
version: 4
last_tested: 2019-02-20
steps:
  - 
    title: Giriş
  - 
    title: Ada Lovelace
  - 
    title: 'Görev: Ada''yı kendini tanıtması için kodla'
    completion:
      - engaged
    challenge: true
  - 
    title: Ada'ya ismini söyle
  - 
    title: Analitik Motor
  - 
    title: Daha fazla şiir
  - 
    title: Analitik Motorun Canlandırılması
    completion:
      - internal
  - 
    title: 'Görev: Şiirinizi kişiselleştirin'
    challenge: true
  - 
    title: 'Görev: Daha fazla kelime'
    challenge: true
  - 
    title: 'Görev: Daha fazla şiir'
    challenge: true
  - 
    title: Sırada ne var?
